### ISSUE TITLE
License setting error on VS2019

### ISSUE THREAD

**Issue by etrianaGIT** [altimesh/hybridizer-basic-samples#106]
I get the following error clicking on Extensions->Hybridized->License Settings

![image](https://user-images.githubusercontent.com/25967992/206311115-8fe2c25f-e265-41d2-afc5-8ef6a13a76b4.png)

I have restarted VS several times and get the same error

**Comment by JeWaVe** [comment]
Hi, 

I can reproduce the issue with visual 2019. 
I will investigate and publish a patch. 
Thanks for reporting;

**Comment by JeWaVe** [comment]
Hi, 

I reproduced and dediced to drop support for old versions of visual studio. VS 2022 introduced many breaking changes which we don't have time to support. 
Hopefully in the next month, everything will go open source (except some core code we want to protect) and the open source community may be able to help you.
