### ISSUE TITLE
Using old versions of the Altimesh Hybridizer Essentials

### ISSUE THREAD

**Issue by KPLK** [altimesh/hybridizer-basic-samples#107]
I know Altimesh Hybridizer Essentials is totally free after the [version 2.0].
But it has dropped support for <10 cuda versions with the start of the version 2.0.
Unfortunately, my graphic card GTX 560 supported maximum cuda version is just cuda 8.0.
So, I decided to download the Altimesh Hybridizer Essentials [version 1.2.10616](https://github.com/altimesh/hybridizer-basic-samples/releases/tag/1.2.10616)
But when I tried to obtain free 3 month license by clicking "Hybridizer>License Settings>3 months free license" it give the error "Something Went Wrong."

Please provide me a solution to get at least the 3 month lisence??

**Comment by JeWaVe** [comment]
Hi, 

Sorry about that. Maintaining so many versions of CUDA turned as a nightmare. 
So far, no easy way. Contact us at contact - at - comua - fr (I'm in charge of support) and we will try to find some solution.
