### ISSUE TITLE
Hybridize Project Error

### ISSUE THREAD

**Issue by sfandres** [altimesh/hybridizer-basic-samples#32]
When I try to Hybridize the Project like it is explained in the getting_started.pdf I received the following error: 

An error ocurred when Hybridizing project ConsoleApplication5 : Could not create and use satellite project from template

I am using Visual Studio 2015 in a windows 10 computer and CUDA Toolkit 8.
Thank you in advance.

**Comment by JeWaVe** [comment]
Hi, I just tried to reproduce your error and wasn't able to do so.
 
I also have a windows 10 computer with visual studio 2015 and cuda 8.0. 
- Did you validate the license before trying to hybridize project?
- Do you have anything different of these version numbers:
    - HybridizerEssentials 1.1.5656.8398
    - visual studio 14.0.25425.01 update 3
    - Cuda compilation tools, release 8.0, V8.0.44 (got it from nvidia-smi). 

Did you perform an update of Hybridizer Essentials or an install from scratch? 

Thank you

**Comment by sfandres** [comment]
It finally works!

I am using Visual Studio v14.0.25431.01 Update 3 with Cuda Toolkit v8.0.61 and I think that the problem was either this Cuda Toolkit version is not supported by Hybridazer or my previous installed Cuda Toolkit was not correctly uninstalled. I bet that the last one was the real cause of the error because recently I had to uninstall Cuda Toolkit 9 and Visual Studio 2017 due to its incompatibility.

Thank you so much for your quick and successful answer.
