### ISSUE TITLE
Missing Intrinsics_CUDA.vs2017.vcxproj

### ISSUE THREAD

**Issue by rbae** [altimesh/hybridizer-basic-samples#37]
The current version in the repository is missing Intrinsics_CUDA.vs2017.vcxproj, which the HybridizerBasicSamples.vs2017.sln has a reference to.

**Comment by JeWaVe** [comment]
Thanks for reporting this issue. 
As a workaround, you can hybridize the c# project. 
We will fix that as soon as possible though.
