### ISSUE TITLE
Unknown error in MonteCarloHeatEquation

### ISSUE THREAD

**Issue by juniorka** [altimesh/hybridizer-basic-samples#41]
When running MonteCarloHeatEquation project I recieve "Display driver stopped responding and has recovered" error in Windows 7and error message in project:

System.ApplicationException is not processed
  HResult = -2146232832
  Message = CUDA error occured before deserialization (most probably during kernel call): unknown error
  Source = Hybridizer.Runtime.CUDAImports
  StackTrace:
       in Hybridizer.Runtime.CUDAImports.CudaSerializationState.CUDADeserializer.InitialVisit (Object param)
       in Hybridizer.Runtime.CUDAImports.NativeSerializerState.UpdateManagedData (Object param)
       in MonteCarloHeatEquation.MonteCarloHeatSolver_wrapped_CUDA.Solve ()
       in CallSite.Target (Closure, CallSite, Object)
       in System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1 [T0] (CallSite site, T0 arg0)
       in MonteCarloHeatEquation.Program.Main (String [] args) in D: \ Work \ hybridizer-basic-samples-master \ sampleNew \ HybridizerBasicSamples_CUDA91 \ 3.Maths \ MonteCarloHeatEquation \ MonteCarloHeatEquation \ Program.cs: line 26
       in System.AppDomain._nExecuteAssembly (RuntimeAssembly assembly, String [] args)
       in System.AppDomain.ExecuteAssembly (String assemblyFile, Evidence assemblySecurity, String [] args)
       in Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly ()
       in System.Threading.ExecutionContext.RunInternal (ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       in System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       in System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, Object state)
       in System.Threading.ThreadHelper.ThreadStart ()
  InnerException:

I use
 - Visual Studio 2015 (version 14.0.25431.01)
 - CUDA 9.1
- GeForce GTX 1060 6GB with driver version 388.19
 
Thank you in advance.

**Comment by JeWaVe** [comment]
Hi, this sample takes quite long to complete.
The issue you have is likely due do WDDM mode setting a default kernel timeout at about 2 seconds. 
Can you open nsight monitor in admin mode and put TDR option at 30, then restart and retry?

**Comment by juniorka** [comment]
Thank you, increasing TDR option was solved the problem!

**Comment by JeWaVe** [comment]
Nice. Can you close the issue?

**Comment by JeWaVe** [comment]
For documentation : in next release, we will automatically detect TDR delay and issue a warning at application startup
