### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by KaiserSozo** [altimesh/hybridizer-basic-samples#43]
I searched information about synchronization, but haven't found it yet. I'm reading info from array and then storing results there, also incrementing values in another array. I assume that I need synchronize it manually. If yes then how better should I do it? Is somewhere an example of calling cuda functions from C#?

**Comment by JeWaVe** [comment]
There are several questions here. 
I can't help you to learn CUDA synchronization and you should refer to (e.g.) stackoverflow.

About Hybridizer, let's take the __syncthreads example : 

You can either do 
CUDAIntrinsics.__syncthreads()
which is exposed in the Hybridizer.Runtime.CUDAImports namespace, 

or do it manually, using [IntrinsicFunctions](http://www.altimesh.com/hybridizer-how-to-intrinsics-2/) : 
```
[IntrinsicFunction("__syncthreads")]
public static void MySyncthreads() { }
```

**Comment by KaiserSozo** [comment]
Ok, how can I call, for example, cudaDeviceSetLimit from CUDA library?

**Comment by JeWaVe** [comment]
cudaDeviceSetLimit is a host function which you have to call before the kernel call. 
It's exposed from cuda object in Hybridizer.Runtime.CUDAImports namespace : DeviceSetLimit

you can run, for example
            cuda.DeviceSetLimit(cudaLimit.cudaLimitStackSize, 12);

heap size is not mapped in our cudaLimit enum (and that is a valid issue), but fortunately, enums are not checked in C#, so you can invoke : 
            cuda.DeviceSetLimit((cudaLimit)thevalueyougetfromthecudaheader, 12);

**Comment by KaiserSozo** [comment]
Thank you for your explanation. I've executed 
cuda.DeviceSynchronize();
            cudaDeviceProp prop;
            cuda.GetDeviceProperties(out prop, 0);
            cudaError_t error = cuda.DeviceSetLimit((cudaLimit)2, 1024 * 1024 * 1024);
            HybRunner runner = HybRunner.Cuda("NeuroC_CUDA.vs2017.dll").SetDistrib(prop.multiProcessorCount * 16, 128);
            wrapper = runner.Wrap(new Program());

DeviceSetLimit returned success. Also tried for 128 Mb and 256 Mb, and anyway I get invalid address in calculation function when allocating memory. Will try to pass allocated buffer

**Comment by JeWaVe** [comment]
Looks like a good idea. However I would recommend to get rid of intermediate buffers whenever possible.
