### ISSUE TITLE
Nsight Cuda debugging don't work in unsafe code

### ISSUE THREAD

**Issue by juniorka** [altimesh/hybridizer-basic-samples#44]
When I starting cuda debugging in Sobel_Lock project, system terminate all. This doing only with unsafe code. How can I debugging and profiling unsafe code in Nsight?

Thank you in advance!

**Comment by juniorka** [comment]
Excuse me, but now I can't reproduce the error. All is OK.

**Comment by JeWaVe** [comment]
Nice. Thanks
