### ISSUE TITLE
Unable to query for a license

### ISSUE THREAD

**Issue by sctjkc01** [altimesh/hybridizer-basic-samples#46]
Visual Studio Community 2015, with C++ support, could not query a license from the configuration tool.  There's a brief moment where it says "Unable to query for a license, contact support", and I'm not getting any license emails.

**Comment by JeWaVe** [comment]
Hi. Thank you for this bug report. 
We’ll have a look at that in the next hours

**Comment by JeWaVe** [comment]
Hi, 
inspecting the log, I see that a request took 7 seconds to complete. 
We have a 5 seconds timeout policy so its likely that UI reported a failure when it shouldn't. 
Could you double check your email?

For further conversation, you can join me directly at 
regis "dot" portalez "at" altimesh "dot" com

Thanks

**Comment by sctjkc01** [comment]
I've been watching my email since I requested a license, and I haven't gotten anything.

**Comment by JeWaVe** [comment]
Hi, I don't see any request failure in the logs. 

Could please request another license so I can inspect what's happening?

Could you also check your spam folder? The email might have landed there for some reason.

**Comment by JeWaVe** [comment]
After some mails, it looks related to your ISP, or something between your machine and azure. 
Could you confirm and close the bug as I can't reproduce your issue?

**Comment by sctjkc01** [comment]
I've actually asked around, including getting a check from other machines (notably, one on a different ISP) but I definitely see this as something that is out of Altimesh's control.  I'd highly suggest checking against various PCs in the US, but Imma go ahead and close it.
