### ISSUE TITLE
How can I get a license if the computer is not allowed to be networked

### ISSUE THREAD

**Issue by DAGUA** [altimesh/hybridizer-basic-samples#51]
My computer  is offline, it seems that I can not receive a license by email. I may need your help, thank you very much.

**Comment by JeWaVe** [comment]
Hi, 

To request first license, computer needs an internet access. 
In very specific cases we can generate them manually. However the process is fairly complex and we don't want to document it publicly. 

You can contact me by mail at regis dot portalez at altimesh[dot]com and explain your issue more specifically. 

Regis

**Comment by DAGUA** [comment]
I have sent an email to the regis dot portalez at gmail[dot]com instead of regis dot portalez at altimesh[dot]com. regis dot portalez at altimesh[dot]com rejected the email I sent by our institute's mail server.
