### ISSUE TITLE
2D Array does not compile

### ISSUE THREAD

**Issue by bigcurl** [altimesh/hybridizer-basic-samples#53]
Attached is a simple project to show that there seems to be a problem with 2D Array support.
The code is correct syntaxwise but does not compile in the hybridizer.

Error		no operator "=" matches these operands             operand types are: hybridizer::hybarray<int64_t, 2> = hybridizer::hybarray<int64_t, 2> * 	IEMA-1_CUDA	C:\spikes\hybridizer-spikes\bug-case\IEMA-1\Program.cs	13	

[bug-case.zip](https://github.com/altimesh/hybridizer-basic-samples/files/2184115/bug-case.zip)

**Comment by bigcurl** [comment]
[bug-case (2).zip](https://github.com/altimesh/hybridizer-basic-samples/files/2184127/bug-case.2.zip)


Uploaded the project

**Comment by JeWaVe** [comment]
Thanks for reporting this issue. 
Bug confirmed. 
As a workaround, you can store to intermediate variables : 

[EntryPoint("run")]
        public static void Run(int N, long[,] ticks, long[,] results)
        {
            for (int k = threadIdx.x + blockDim.x * blockIdx.x; k < N; k += blockDim.x * gridDim.x)
            {
                long t0 = ticks[k, 0];
                long t1 = ticks[k, 0];
                long t2 = ticks[k, 0];
                results[k, 0] = t0;
                results[k, 1] = t1;
                results[k, 2] = t2;
            }
        }

**Comment by JeWaVe** [comment]
Issue is solved. 
Next release will be OK

**Comment by JeWaVe** [comment]
resolved as version 9554
