### ISSUE TITLE
Can't get any license

### ISSUE THREAD

**Issue by vectorix** [altimesh/hybridizer-basic-samples#58]
I got trial a license key and it does not validate. It just sits on "Loading" and does nothing.
Tried multiple times.
Is the licensing working?

**Comment by JeWaVe** [comment]
Hi, 

I repro the issue. 

It was working and it's now broken for some yet unknown reason.

**Comment by JeWaVe** [comment]
We have a server side problem. 
Good news is nobody will have to reinstall. 
Should be solved soon.
