### ISSUE TITLE
Commercial license terms

### ISSUE THREAD

**Issue by vectorix** [altimesh/hybridizer-basic-samples#61]
Hi team,

I can't seem to find the details of the commercial license terms on http://www.altimesh.com/.

What I assume/expect is that the commercial term gives me 1 year of updates and support. After that, I assume the released binaries released to customers and my local development environment will continue to work, but I will not get any future updates, for example, for new CUDA versions, I need to renew the subscription. Is that correct?

Also, for a single license, is there multi seat activation, or do I need to purchase one license per seat i.e. it is machine locked?

Thanks

**Comment by JeWaVe** [comment]
Hybridizer Essentials commercial license grants you 1 year on 1 machine only. 
After that date, generated code will still run on your machine, but you won't be able to generate it again. 
Generated code can only run on the machine it has been compiled on. It can't be shipped to third-parties. 
Third parties can compile and run your C# code if they also have a valid license. 

We plan to make a redistributable version, but price won't be the same.
