### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by truongan012** [altimesh/hybridizer-basic-samples#63]
Hello,
I've got an error when installing new version 9833, it show as below
Error 1001
![image](https://user-images.githubusercontent.com/13611865/47251790-0e34eb00-d463-11e8-8c53-1aa36e6dd368.png)

It causes the CudaImports library is not available for use. Then, project can not be compiled.
I'm using latest visual studio 2017 with update 8 and cuda 10.0.
Could you check and tell me how to fix it.

**Comment by JeWaVe** [comment]
Hi,

Thanks for the bug report. 
Could you attach the installer log please? 

Regards

Régis Portalez

**Comment by truongan012** [comment]
Hi,
Here is the log
[VSIXInstaller_d4d3846e-d40a-4852-8d96-bc3028635cc6.log](https://github.com/altimesh/hybridizer-basic-samples/files/2498853/VSIXInstaller_d4d3846e-d40a-4852-8d96-bc3028635cc6.log)

**Comment by JeWaVe** [comment]
Hi, 

Issue identified. 
We rely on VSIXInstaller to install our visual studio extension. 
VSIXInstaller is part of windows SDK, and not present on all machines. 

Need to figure out a solution (redistribute vsixinstaller, or go back to manual vsix installation)

In the meantime, please install vsixinstall / windows SDK and that should solve the issue.

**Comment by truongan012** [comment]
Hello, 
I figure out the issue now. 
Need to install the version 9554 first, then install the latest one.

**Comment by rrperkin** [comment]
This is also happening to me. I don't know where or how to get the "version 9554" that @truongan012 said fixed the issue. I have added the Visual Studio SDK and the Windows SDK and the toolset you directed.

**Comment by MuSamiNaf** [comment]
I am having the same exact problem as truongan012..
Visual Studio 2017 15.2 (26430.6)
Windows 10 SDK installed
Visual Studio SDK installed

How to solve it?

**Comment by JeWaVe** [comment]
Could you please check if this pre-release fixes the issue? 

https://github.com/altimesh/hybridizer-basic-samples/releases/tag/1.2.10108

**Comment by JeWaVe** [comment]
@rrperkin you can find older releases in the "releases" tab of this repo. 

Here is 9554 : https://github.com/altimesh/hybridizer-basic-samples/releases/tag/1.1.9554

**Comment by Shylie** [comment]
I'm having this issue on the latest version available [here](https://marketplace.visualstudio.com/items?itemName=altimesh.AltimeshHybridizerExtensionEssentials)
![image](https://user-images.githubusercontent.com/28541112/59232048-e42a6780-8bb0-11e9-805c-1e4bb723589d.png)

**Comment by qcmiao1998** [comment]
I meet the problem on win10 1903 and vs2019.
