### ISSUE TITLE
__shared__memory

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#68]
I have a confusion that how can I use sharedmemory(which is "__shared__" in C++) in  hybridizer? I want to use my Hybridizer program to get the maximum value or minimum value from a matrix or a picture.  I think some strategies by using sharedmemory can make the Gpu work faster.

**Comment by JeWaVe** [comment]
Hi, 

you can use sharedmemory by using our special type "SharedMemoryAllocator". 
for example : 

`int[] buffer = new SharedMemoryAllocator<int>.allocate(32);`

will use 32 * sizeof(int) bytes of shared memory on the device. 
To have this memory actually available, you need to configure your kernel call with additional arguments : 

`HybRunner.Cuda().SetDistrib(gridDim, 1, blockDim, 1, 1, 32 * sizeof(int)).Wrap(myinstance).MyKernel()...`

You can find an example in our [reduction samples](https://github.com/altimesh/hybridizer-basic-samples/blob/master/HybridizerBasicSamples_CUDA100/7.Advanced/LambdaReduction/LambdaReduction/Program.cs) or in our [matrix multiplication sample](https://github.com/altimesh/hybridizer-basic-samples/blob/master/HybridizerBasicSamples_CUDA100/3.Maths/SharedMatrix/SharedMatrix/Program.cs)

**Comment by xiyunqiao** [comment]
Thanks for your advice！
