### ISSUE TITLE
FFT Calculation

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#69]
How can I use hybridizer to make a fft calculation for a one-dimensional array?
I hope altimesh can release a sample to teach us how to use fft .
Thank you.

**Comment by xiyunqiao** [comment]
Thank you，I am trying to use [cufft] in hybridizer in cuda 8.0 to do my research. I am looking forward to the more samples added in hybridizer. 






------------------ 原始邮件 ------------------
发件人: "Portalez Régis"<notifications@github.com>;
发送时间: 2019年1月8日(星期二) 下午4:35
收件人: "altimesh/hybridizer-basic-samples"<hybridizer-basic-samples@noreply.github.com>;
抄送: "品茶。忆流年"<1054330225@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [altimesh/hybridizer-basic-samples] FFT Calculation (#69)




You can use [cufft] to perform any kind of fast fourier transforms.
 This is mapped in hybridizer to cuda 9.0.
 I'll add 9.1, 9.2 and 10.0 soon.
 
Another option is to manually program your fft in C# and hybridize it. That should work, but be slightly slower than the nvidia-tuned library.
 
I'll add a sample, as this is indeed a important library.

**Comment by JeWaVe** [comment]
Here is a sample, which is working with our internal development version : https://github.com/altimesh/hybridizer-basic-samples/tree/january_update/HybridizerBasicSamples_CUDA100/5.CUDA%20runtime/SimpleCufft
With the current production release of hybridizer essentials, basic cufft API is already supported, and you should be able to adapt this sample to match your needs. 

It works with CUDA 9.0/9.1/9.2/10.0. 

I'm sorry but we won't improve our support of cuda 8.0 unless a premium customer request it. 
You should consider moving to CUDA 10.0 to get latest goodness.

**Comment by JeWaVe** [comment]
release is published.
