### ISSUE TITLE
HybridizerBasicSamples_CUDA100

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#71]
I have installed cuda 10.0 in my computer. But when I open the project "HybridizerBasicSamples_CUDA100" , only the sample "simple cufft" can work in cuda 10.0,other samples can not work.

The error visual studio show me is that  ---> System.ApplicationException: Dll load error when loading C:\Program Files\Altimesh\Hybridizer Essentials\bin\Hybridizer.PTXJitterService.9.2.exe: 126	

why  it shows Hybridizer.PTXJitterService.9.2.exe  but not Hybridizer.PTXJitterService.10.0.exe?

**Comment by JeWaVe** [comment]
Very good catch. 
Indeed that's an issue, I forgot to update the jitter version. Didn't notice on any test machine, since they all have cuda 9.2 installed. 
You can replace 9.2 by 10.0 and it should work. 
I'll commit the fix immediately. 
Thanks

**Comment by burybury** [comment]
just got this issue in the vs marketplace version + cuda 10 project 
the fix for jutter was only inlcuded in the 10.1 ssample as i see from the commits description
