### ISSUE TITLE
Missing .dll When Running HelloWorld Example

### ISSUE THREAD

**Issue by SmittyD-92** [altimesh/hybridizer-basic-samples#74]
I haven't been able to run the CUDA100 examples due to many build errors, the main one being: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\dcorrell\Desktop\hybridizer-basic-samples-master\hybridizer-basic-samples-master\HybridizerBasicSamples_CUDA100\x64\Debug\hybridizer_cuda_reduction.dll" because it was not found.	ConjugateGradient (3.Maths\ConjugateGradient\ConjugateGradient)			

-------------------------------------------------------------------------------------------------------------------

Furthermore, when attempting to run the HelloWorld example individually, I'm getting: System.ApplicationException: 'Dll load error when loading HelloWorld_CUDA.dll: 126'. After attempting to run the HelloWorld application individually I get the message that the HelloWorld_CUDA.dll does not exist.

Here's the full error: 

System.ApplicationException
  HResult=0x80131600
  Message=Dll load error when loading HelloWorld_CUDA.dll: 126
  Source=Hybridizer.Runtime.CUDAImports
  StackTrace:
   at Hybridizer.Runtime.CUDAImports.Win32KernelInteropTools.LoadLibrary(String libName)
   at Hybridizer.Runtime.CUDAImports.HybRunner..ctor(String dllName, HybridizerFlavor flavor, AbstractNativeMarshaler marshaller)
   at Hybridizer.Runtime.CUDAImports.HybRunner.Cuda(String dllName)
   at HelloWorld.Program.Main(String[] args) in C:\Users\dcorrell\Desktop\hybridizer-basic-samples-master\hybridizer-basic-samples-master\HybridizerBasicSamples_CUDA100\1.Simple\HelloWorld\HelloWorld\Program.cs:line 37

----------------------------------------------------------------------------------------------------------------

I believe that these errors are related, and I'm not sure how to fix them.  Are there missing .dll files from the download, or maybe this is a path issue? 

Thank you!

**Comment by JeWaVe** [comment]
Hi, 

Thank you for reporting the first issue. It's now fixed in our development branch (https://github.com/altimesh/hybridizer-basic-samples/tree/february-update). 

For the second : did you build projects in the floowing order:
- C# project
- CUDA project
- run C#
?

**Comment by SmittyD-92** [comment]
Hi, 

The issue was with the CUDA build. It was targeting windows SDK version 8 when it should have been targeting SDK version 10. After switching that it ran fine. 

Thank you for your help!

**Comment by JeWaVe** [comment]
Hi, 
Thanks for reporting issue and solution!

**Comment by jdahaldev** [comment]
I get this error with cuda 10.0, visual studio 2017 community, using toolset v141. 
I downloaded cuda 10.0 for windows 10.
