### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#75]
Hello，my first free license has been expired,I have applied a new free license,but when I program in my vs2013,it shows errors:[FATAL] : [ERROR] LicenseException: Invalid license	
Please help me for it,thank you very much!

**Comment by xiyunqiao** [comment]
<img width="522" alt="_20190220214134" src="https://user-images.githubusercontent.com/39361634/53095649-59b5ed80-3558-11e9-8dc6-f6715bc688b7.png">

**Comment by JeWaVe** [comment]
Hi, 
Free licenses are valid for 3 months. 
After that you can purchase the 1 year valid license for 200€ per year per machine. 
That's stated in our terms and conditions. 
You can also apply for hobbyist or acadamic subscriptions if that's applicable.

**Comment by xiyunqiao** [comment]
Hello,I have send a email by my university email to"contact@altimesh.com"to apply for an academic subscription,but it replys me that"We do not address technical issues on this email address." Please tell me how to apply for an academic subscriptions,thanks!
