### ISSUE TITLE
Academic subscription

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#76]
Hello,I have send a email by my university email to"[contact@altimesh.com](mailto:contact@altimesh.com)"to apply for an academic subscription,but it replys me that"We do not address technical issues on this email address." Please tell me how to apply for an academic subscriptions,thanks!

**Comment by JeWaVe** [comment]
That’s the right way. 
We did something wrong. Please apply again. 
Sorry for the inconvenience

**Comment by xiyunqiao** [comment]
Thanks!
I have applied it at"contact@altimesh.com" again,
hope I can get the academic subscription soon.

**Comment by JeWaVe** [comment]
I granted you an academic subscription.
