### ISSUE TITLE
Altimesh Hybridizer C# Usage

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#78]
![_20190225164705](https://user-images.githubusercontent.com/39361634/53324933-10311e00-391d-11e9-9995-aaf82edb8090.png)

Hello，I want to use cuda in my former application writen by C#. I found that "Aitimesh Hybridizer C# Usage" is a .cs which provide a method to use hybridizer in .net. 
I want to ask that if there be a sample to show how to use "Aitimesh Hybridizer C# Usage"in a normal C# programme without build a "Aitimesh Hybridizer sample project".

Thanks!

**Comment by JeWaVe** [comment]
you have a button "Hybridize Project" when you right click the C# project.

**Comment by xiyunqiao** [comment]
Thank you very much!
