### ISSUE TITLE
Cufft in Hybridizer

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#79]
using Hybridizer.Runtime.CUDAImports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

using Complex = Hybridizer.Runtime.CUDAImports.double2;

namespace Test_2_25
{
    class Program
    {

        [EntryPoint("mulitiply")]
        public static void mulitiply(Complex[] a, double[] b, int n)
        {
            int numThreads = blockDim.x * gridDim.x;
            int threadID = blockIdx.x * blockDim.x + threadIdx.x;

            for (int i = threadID; i < n; i += numThreads)
            {
                a[i].x *= b[i];
                a[i].y *= b[i];
            }
        }

        static void Main(string[] args)
        {
            int Length = 8;
            Complex[] h_signal = new Complex[Length];
            double[] b = new double[Length];
            for (int i = 0; i < Length; i++)
            {
                h_signal[i].x = 1;
                h_signal[i].y = 0.0d;
                b[i] = 1.05;
            }

            int mem_size = Length *2*sizeof(double);
            GCHandle signalHandle = GCHandle.Alloc(h_signal, GCHandleType.Pinned);

            IntPtr d_signal;
            cuda.ERROR_CHECK(cuda.Malloc(out d_signal, mem_size));

            cuda.ERROR_CHECK(cuda.Memcpy(d_signal, signalHandle.AddrOfPinnedObject(), mem_size, cudaMemcpyKind.cudaMemcpyHostToDevice));

            cufftHandle plan;
            cufft_ERROR_CHECK(cufft.Plan1d(out plan, Length, cufftType.CUFFT_C2C, 1));

            cufft_ERROR_CHECK(cufft.ExecC2C(plan, d_signal, d_signal, -1));

            dynamic wrapped = HybRunner.Cuda().SetDistrib(32, 256).Wrap(new Program());
            wrapped.mulitiply(d_signal, b, Length);

            cuda.ERROR_CHECK(cuda.Memcpy(signalHandle.AddrOfPinnedObject(), d_signal, mem_size, cudaMemcpyKind.cudaMemcpyDeviceToHost));

            cufft_ERROR_CHECK(cufft.Destroy(plan));
            signalHandle.Free();
            cuda.ERROR_CHECK(cuda.Free(d_signal));

            for (int i = 0; i < Length; i++)
            {
                Console.Write("{0}", h_signal[i].x);
            }

            for (int i = 0; i < Length; i++)
            {
                Console.Write("{0}", h_signal[i].y);
            }

            Console.Out.WriteLine(" OK");
        }

        static void cufft_ERROR_CHECK(cufftResult result)
        {
            if (result != cufftResult.CUFFT_SUCCESS)
            {
                Console.Error.WriteLine(Enum.GetName(typeof(cufftResult), result));
                Environment.Exit(6); 
            }
        }

    }
}

**Comment by xiyunqiao** [comment]
Hello,I am trying to make a simple cufft for an array with the length of 8. I learn from the sample “simplecufft” of Hybridizer. The Type of parameter “d_signal” is IntPtr,it can compile correctly in the sample,but when I compile my programme,it shows the mistake”The best overloaded method match for XXXX has some invalid arguments”.
I am confused that why the Intptr in the sample can compile correctly in the EntryPoint “ComplexPointwiseMulAndScale” which argument is Complex but not Intptr.

**Comment by JeWaVe** [comment]
You cannot mix IntPtr with managed arguments. 
You have to use either: 
mutiply(Complex[], double[], int)
or 
multiply(IntPtr, IntPtr, int)


```csharp
using Hybridizer.Runtime.CUDAImports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

using Complex = Hybridizer.Runtime.CUDAImports.double2;

namespace Test_2_25
{
    class Program
    {
        [EntryPoint("mulitiply")]
        public static void mulitiply(Complex[] a, double[] b, int n)
        {
            int numThreads = blockDim.x * gridDim.x;
            int threadID = blockIdx.x * blockDim.x + threadIdx.x;

            for (int i = threadID; i < n; i += numThreads)
            {
                a[i].x *= b[i];
                a[i].y *= b[i];
            }
        }


        static void Main(string[] args)
        {
            int Length = 8;
            Complex[] h_signal = new Complex[Length];
            double[] b = new double[Length];
            for (int i = 0; i < Length; i++)
            {
                h_signal[i].x = 1;
                h_signal[i].y = 0.0d;
                b[i] = 1.05;
            }

            int mem_size = Length * 2 * sizeof(double);
            GCHandle signalHandle = GCHandle.Alloc(h_signal, GCHandleType.Pinned);
            GCHandle bHandle = GCHandle.Alloc(b, GCHandleType.Pinned);
            IntPtr d_signal, d_b;
            cuda.ERROR_CHECK(cuda.Malloc(out d_signal, mem_size));
            cuda.ERROR_CHECK(cuda.Malloc(out d_b, Length * sizeof(double)));

            cuda.ERROR_CHECK(cuda.Memcpy(d_signal, signalHandle.AddrOfPinnedObject(), mem_size, cudaMemcpyKind.cudaMemcpyHostToDevice));
            cuda.ERROR_CHECK(cuda.Memcpy(d_b, bHandle.AddrOfPinnedObject(), Length * sizeof(double), cudaMemcpyKind.cudaMemcpyHostToDevice));

            cufftHandle plan;
            cufft_ERROR_CHECK(cufft.Plan1d(out plan, Length, cufftType.CUFFT_C2C, 1));

            cufft_ERROR_CHECK(cufft.ExecC2C(plan, d_signal, d_signal, -1));

            dynamic wrapped = HybRunner.Cuda().SetDistrib(32, 256).Wrap(new Program());
            wrapped.mulitiply(d_signal, d_b, Length);

            cuda.ERROR_CHECK(cuda.Memcpy(signalHandle.AddrOfPinnedObject(), d_signal, mem_size, cudaMemcpyKind.cudaMemcpyDeviceToHost));

            cufft_ERROR_CHECK(cufft.Destroy(plan));
            signalHandle.Free();
            cuda.ERROR_CHECK(cuda.Free(d_signal));

            for (int i = 0; i < Length; i++)
            {
                Console.Write("{0}", h_signal[i].x);
            }

            for (int i = 0; i < Length; i++)
            {
                Console.Write("{0}", h_signal[i].y);
            }

            Console.Out.WriteLine(" OK");
        }

        static void cufft_ERROR_CHECK(cufftResult result)
        {
            if (result != cufftResult.CUFFT_SUCCESS)
            {
                Console.Error.WriteLine(Enum.GetName(typeof(cufftResult), result));
                Environment.Exit(6);
            }
        }

    }
}
```
