### ISSUE TITLE
Error in .vcxproj

### ISSUE THREAD

**Issue by SmittyD-92** [altimesh/hybridizer-basic-samples#80]
Hi,

After hybridizing my C# project, and building it, I get an error when attempting to build the .vcxproj. 

The error is as follows (from the end of the build output):

1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error : [ERROR] : 0X605D : cannot create an instance of a gc type within hybridized code
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error : [ERROR] : Exception in Hybridizer Main: INTERNAL ERROR

---------------------------------------------------------------------------------------------------------------

I get many conflicting assembly warnings prior to the error, so perhaps that is the main cause of the issue. Any help would be greatly appreciated.

Thank you!

**Comment by JeWaVe** [comment]
That means you creating an instance on heap, using new A() where A is a class.
It’s indeed not supported , as stated in our doc.
