### ISSUE TITLE
CUFFT

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#81]
Hello，will the hybridizer  can support the "double" type in cufftType -"ExecR2c " in the future? sometimes the float type can not fit well.
Thanks.

**Comment by xiyunqiao** [comment]
Thank you!

**Comment by axelanglet** [comment]
Hello, after some research, we discovered a bug with [ExecD2Z](https://docs.nvidia.com/cuda/cufft/index.html#function-cufftexecr2c-cufftexecd2z) (which is ExecR2C with double precision). We will resolve it in future release. But you can bypass it by using `IntPtr`.

```csharp
double[] p = new double[size * size];
IntPtr p_ptr = CudaMarshaler.Instance.MarshalManagedToNative(p);

double2[] P = new double2[size * (size + 1)];
IntPtr P_ptr = CudaMarshaler.Instance.MarshalManagedToNative(P);

cufftHandle handle;

cufft.Plan2d(out handle, size, size, cufftType.CUFFT_D2Z);
            
cufft.ExecD2Z(handle, p_ptr, P_ptr);
```

**Comment by xiyunqiao** [comment]
Thanks a lot，can you tell me when I finish my fft by your way,how can i transfer the data from the device to host by intptr?

**Comment by axelanglet** [comment]
Sorry I forgot to write how to retrieve data on the host. Now this will be working fine.

```csharp
double[] p = new double[size * size];
IntPtr p_ptr = CudaMarshaler.Instance.MarshalManagedToNative(p);

double2[] P = new double2[size * (size + 1)];
IntPtr P_ptr = CudaMarshaler.Instance.MarshalManagedToNative(P);

cufftHandle handle;

cufft.Plan2d(out handle, size, size, cufftType.CUFFT_D2Z);
            
cufft.ExecD2Z(handle, p_ptr, P_ptr);

//retrieve data
CudaMarshaler.Instance.CleanUpNativeData(p_ptr);
CudaMarshaler.Instance.CleanUpNativeData(P_ptr);
```

**Comment by xiyunqiao** [comment]
Hello，I have a issue that if the result of fft is minus,the hybridizer cufft will show zero,why hybridizer can not show the real result of minus?
Thanks.

**Comment by JeWaVe** [comment]
What does that mean?
Please open separate issue, and provide code reproducer with an accurate description of the issue you face.

**Comment by xiyunqiao** [comment]
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.Diagnostics;
using Hybridizer.Runtime;
using Complex = Hybridizer.Runtime.CUDAImports.double2;

namespace Hype3_16
{
    class Program
    {

        static void Main(string[] args)
        {

            int Length = 16;
            Complex[] h_signal = new Complex[Length];
            Complex[] b = new Complex[Length];
            double[] a = new double[Length];

            for (int i = 0; i < Length-1; i++)
            {
                a[i] = 1.1d;
            }
            a[Length - 1] = 1.2d;
            IntPtr signal_R = CudaMarshaler.Instance.MarshalManagedToNative(a);
            IntPtr signal_C = CudaMarshaler.Instance.MarshalManagedToNative(h_signal);

            cufftHandle handle;

            cufft.Plan1d(out handle, Length, cufftType.CUFFT_D2Z, 1);
            cufft.ExecD2Z(handle, signal_R, signal_C);

            cuda.DeviceSynchronize();
            CudaMarshaler.Instance.CleanUpNativeData(signal_R);
            CudaMarshaler.Instance.CleanUpNativeData(signal_C);

            for (int i = 0; i < Length; i++)
            {
                Console.Out.WriteLine("{0} ", h_signal[i].y);
            }



        

        }

        static void cufft_ERROR_CHECK(cufftResult result)
        {
            if (result != cufftResult.CUFFT_SUCCESS)
            {
                Console.Error.WriteLine(Enum.GetName(typeof(cufftResult), result));
                Environment.Exit(6);
            }
        }

    }
}
