### ISSUE TITLE
minus in hybridizer

### ISSUE THREAD

**Issue by xiyunqiao** [altimesh/hybridizer-basic-samples#82]
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.Diagnostics;
using Hybridizer.Runtime;
using Complex = Hybridizer.Runtime.CUDAImports.double2;

namespace Hype3_16
{
class Program
{

    static void Main(string[] args)
    {

        int Length = 16;
        Complex[] h_signal = new Complex[Length];
        Complex[] b = new Complex[Length];
        double[] a = new double[Length];

        for (int i = 0; i < Length-1; i++)
        {
            a[i] = 1.1d;
        }
        a[Length - 1] = 1.2d;
        IntPtr signal_R = CudaMarshaler.Instance.MarshalManagedToNative(a);
        IntPtr signal_C = CudaMarshaler.Instance.MarshalManagedToNative(h_signal);

        cufftHandle handle;

        cufft.Plan1d(out handle, Length, cufftType.CUFFT_D2Z, 1);
        cufft.ExecD2Z(handle, signal_R, signal_C);

        cuda.DeviceSynchronize();
        CudaMarshaler.Instance.CleanUpNativeData(signal_R);
        CudaMarshaler.Instance.CleanUpNativeData(signal_C);

        for (int i = 0; i < Length; i++)
        {
            Console.Out.WriteLine("{0} ", h_signal[i].y);
        }

    

    }

    static void cufft_ERROR_CHECK(cufftResult result)
    {
        if (result != cufftResult.CUFFT_SUCCESS)
        {
            Console.Error.WriteLine(Enum.GetName(typeof(cufftResult), result));
            Environment.Exit(6);
        }
    }

}
}

**Comment by xiyunqiao** [comment]
Hello，I have a issue that if the result of fft is negative number,the hybridizer cufft will show zero,why hybridizer can not show the real result of negative number?
Thanks.

**Comment by xiyunqiao** [comment]
The true result is 0 0.0382683432365089 0.0707106781186545 0.0923879532511285 0.0999999999999996 0.0923879532511286 0.0707106781186545 0.0382683432365089 0 -0.0382683432365089 -0.0707106781186545 -0.0923879532511286 -0.0999999999999996 -0.0923879532511285 -0.0707106781186545 -0.0382683432365089

But the hybridizer shows 0 0.0382683432365089 0.0707106781186545 0.0923879532511286 0.0999999999999996 0.0923879532511286 0.0707106781186545 0.0382683432365089 0 0 0 0 0 0 0 0

The negative numbers were showed as zero，it confuses me.

**Comment by JeWaVe** [comment]
Hi. In that Sample Hybridizer does nothing more than invoke cufft under the hood (pinvoke). 

When I write the same thing in CUDA, I get the same thing : 

```
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include "cufft.h"
#include <cstdlib>
#include <cstdio>

void cufft_ERROR_CHECK(cufftResult result);

int main() 
{
	int Length = 16;
	cufftDoubleComplex* h_signal = new cufftDoubleComplex[Length];
	cufftDoubleComplex* b = new cufftDoubleComplex[Length];
	double* a = new double[Length];

	for (int i = 0; i < Length - 1; i++)
	{
		a[i] = 1.1;
	}
	a[Length - 1] = 1.2;

	double* signal_R;
	cufftDoubleComplex* signal_C;
	cudaMalloc(&signal_R, Length * sizeof(double));
	cudaMalloc(&signal_C, Length * sizeof(cufftDoubleComplex));
	cudaMemcpy(signal_R, a, Length * sizeof(double), cudaMemcpyHostToDevice);

	cufftHandle handle;

	cufftPlan1d(&handle, Length, cufftType::CUFFT_D2Z, 1);
	cufftExecD2Z(handle, signal_R, signal_C);

	cudaMemcpy(h_signal, signal_C, Length * sizeof(cufftDoubleComplex), cudaMemcpyDeviceToHost);

	for (int i = 0; i < Length; i++)
	{
		::printf("%lf\n", h_signal[i].y);
	}
}

void cufft_ERROR_CHECK(cufftResult result)
{
	if (result != cufftResult::CUFFT_SUCCESS)
	{
		::fprintf(stderr, "error : %d\n", result);
		::abort();
	}
}
```

**Comment by xiyunqiao** [comment]
Thanks for your experiment in cuda !
Maybe I should find another solution.

**Comment by JeWaVe** [comment]
What do you mean? 
CUDA and Hybridizer give the same result. I guess the problem is in your code.

**Comment by xiyunqiao** [comment]
ok，I will check my code first. Thank you very much.
