### ISSUE TITLE
DLL not being generated

### ISSUE THREAD

**Issue by tntristan12** [altimesh/hybridizer-basic-samples#83]
I'm a little rusty with writing bug reports so I will probably edit this frequently within the first few hours of posting. That said, I made sure to hit all of the items on the checklist:

 - [**YES**] I have installed C++ support in Visual Studio.
 - [**YES**] I have queried and validated a license for Hybridizer Essentials and your license is still valid (Tools->Hybridizer Configuration) (_I have just recently started the free trial period_).
 - [**YES**] I have CUDA 8 or 9.x installed and Visual Studio Integration enabled (_Specifically 9.2_).
 - [**YES**] I run CUDA 9.x with visual 2017, and I have installed v140 toolset and compiled the native project with this toolset.

So, in essence, I keep trying to hybridize my project, and no matter how many times I've done it, there is no DLL for me to use with HybRunner. On top of that, the CUDA satellite project just fails to build (see attached log for details). I suspect that hybridizer.wrappers.cu is not being generated properly and hybridizer.generated.cpp just doesn't even exist (more details are attached below).

I know I'm doing _something_ right, because the hybridizer has run just fine when I've tried to implement the Hello World example, so that's a positive sign. I haven't tried implementing the Mandelbrot example, but that's essentially what my project is (just with more bells and whistles).

Please message me if you need more information about my project or the issue I'm experiencing. Otherwise, see below for more information.

**Some additional information that I will update as I think of it:**

- Here's the log file from the failed build: [Mandelbrottyzeug_CUDA.log](https://github.com/altimesh/hybridizer-basic-samples/files/2998909/Mandelbrottyzeug_CUDA.log)

- Here is the file in question where I am attempting to implement the hybridizer: [MandelbrotDouble.txt](https://github.com/altimesh/hybridizer-basic-samples/files/2998910/MandelbrotDouble.txt)

- Here is the generated hybridizer.wrappers.cu: [hybridizer.wrappers.cu.txt](https://github.com/altimesh/hybridizer-basic-samples/files/2998999/hybridizer.wrappers.cu.txt)

- Note that the hybridizer.wrappers.cu file generated looks really weird between lines 54 and 104. In fact, that's where the IComparable error is getting thrown. So I think I'm doing something wrong somehow, but I'm not sure what. I've tried this a few times with this project and it doesn't seem to want to work. (The error is being thrown on line 73, by the way)

- FYI I am running on a GeForce GTX 1080 using Windows 10, Visual Studio 2017 (Community version), CUDA 9.2, and the latest version of Hybridizer.

- I just attempted the same procedure using CUDA 10.0 and got the same error. Here is the updated crash log: [Mandelbrottyzeug_CUDA.log](https://github.com/altimesh/hybridizer-basic-samples/files/2999042/Mandelbrottyzeug_CUDA.log)

**UPDATE:**

I'm having some preliminary success with pasting my project files into a new project that I created to use Hybridizer from the beginning.

**Comment by tntristan12** [comment]
[Mandelbrottyzeug_CUDA.log](https://github.com/altimesh/hybridizer-basic-samples/files/2998909/Mandelbrottyzeug_CUDA.log)

Here's the log file from the failed build.

**Comment by tntristan12** [comment]
[MandelbrotDouble.txt](https://github.com/altimesh/hybridizer-basic-samples/files/2998910/MandelbrotDouble.txt)

Here is the file in question where I am attempting to implement the hybridizer.

**Comment by tntristan12** [comment]
[hybridizer.wrappers.cu.txt](https://github.com/altimesh/hybridizer-basic-samples/files/2998999/hybridizer.wrappers.cu.txt)

The hybridizer.wrappers.cu file generated looks really weird between lines 54 and 104. In fact, that's where the IComparable error is getting thrown. So I think I'm doing something wrong somehow, but I'm not sure what. I've tried this a few times with this project and it doesn't seem to want to work.

**Comment by tntristan12** [comment]
(the error is being thrown on line 73, by the way)

**Comment by JeWaVe** [comment]
Hi, 

It seems you're using multidimensional arrays : 
`found type <System.Double[,]> used by` 

To enable that, you need to change an option in the native project, as it's done in that sample : 
https://github.com/altimesh/hybridizer-basic-samples/tree/master/HybridizerBasicSamples_CUDA100/2.Imaging/Sobel_2D

![image](https://user-images.githubusercontent.com/11440561/55707416-d9522b80-59e3-11e9-8f49-5c84b8bac5b8.png)

In addition, it seems you're using some .Net types which may be not supported : 
`found type <System.ValueTuple`3> used by`

Keep in mind we don't support entire .Net ecosystem. 
You might want to use your own types, or use builtins / intrinsics. 
https://github.com/altimesh/hybridizer-basic-samples/tree/master/HybridizerBasicSamples_CUDA100/1.Simple/Builtin

https://github.com/altimesh/hybridizer-basic-samples/tree/master/HybridizerBasicSamples_CUDA100/1.Simple/Intrinsics

Please keep us posted

**Comment by JesusSanjuan** [comment]
I have the same problem, did you somehow manage to generate the dll?

**Comment by JeWaVe** [comment]
Hi, 

update on this issue. 
there are many errors which are due to the fact that Hybridizer doesn't support the entire .Net framework. Sometimes because of internal limitations, sometimes because of CUDA limitations. 

- valuetuple<> is not supported and wont be. 
- entrypoint must return void (that is a CUDA requirement)
- multidimensional array assignment in device code is not supported (but could be)
- nullable type is partially implemented. You can declare an builtin type (http://docs.altimesh.com/articles/ProgrammingGuide.html#builtins)
- math.log(x, b) is not implemented. It must be 
```
[IntrinsicFunction("log2")]
public static double Log2(double x)
{
    return Math.Log(x, 2.0);
}
```
Best regards
