### ISSUE TITLE
Any news about CUDA 10.2 support?

### ISSUE THREAD

**Issue by ThorMutoAsmund** [altimesh/hybridizer-basic-samples#91]
Please make sure items below are checked before creating a new issue:

 - [] You run Visual Studio 2012, 2013, 2015 or 2017 with a valid license
 - [] You installed C++ support in Visual Studio
 - [] You queried and validated a license for Hybridizer Essentials and your license is still valid (Tools->Hybridizer Configuration)
 - [] You have CUDA 8 or 9.x installed and Visual Studio Integration enabled
 - [] If you run cuda 9.x with visual 2017, you have installed v140 toolset and compile native project with this toolset.

**Comment by JeWaVe** [comment]
Now supported with version 2.0.2 (only vs 2022 though)
