### ISSUE TITLE
Using for dataset creation

### ISSUE THREAD

**Issue by joshisunil-1983** [altimesh/hybridizer-basic-samples#98]
Hello @JeWaVe ,

hybridizer can be used? to create Numerous data tables from data objects like class objects etc.

In my case, one of my window applications used to perform data calculations is taking time to fill calculated variable results in data tables. I want to run this part on GPU so that performance can be achieved.

may I proceed with this using hybridizer? Please guide.

**Comment by JeWaVe** [comment]
Sorry, please contact me at contact - at - comua .dot- fr for non bug/feature related questions.
